# 开发环境配置
server:
  port: 8081
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Q!W@e3r4t5
    url: jdbc:mysql://106.14.152.86:3306/dsms_test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
  #    password: 12345678
  thymeleaf:
    cache: false
  #国际化配置
  messages:
    basename: i18n.login
  # 邮箱配置
  mail:
    host: smtp.163.com
    port: 587
    username: lkn301415@163.com
    password: AJOCTQQRHPRNRRZA
    # qq: tloznuenqurqjijb
    protocol: smtps
    default-encoding: utf-8
    from: lkn301415@163.com
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false

#自定义文件访问路径
myfile:
  #path: D:\\A_linshi
  #filePath: D:\\test_Jar\\syds.pdf
  path: /test/ImpFile
  filePath: /test/syds/syds.pdf